name: Welcome note

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: 'Welcome note for using Docker'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
       
      - name:  'Build and  push image'
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u 'hshanmuk' --password-stdin
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          docker push my-image-name:latest

